### ISSUE TITLE
wrong color walk of shame

### ISSUE THREAD

**Issue by jonosterman** [maugier/ascii-flags#1]
what a shame! you betrayed us by coloring our proud national symbol with wrong colors!

actually it seems you re-use current terminal color (like white). In case of swiss flag, and due to the fact that I use funky l337 73rm1n4l 53771n65 with green/black in my over 9000 i3 terminal : swiss flag display a green cross.

whatever : great project. keeps going !

**Comment by maugier** [comment]
Oh noes, my honor is forever tainted by this abominable mistake. Thanks the Flying Spaghetti Monster I was able to fix this quickly at last, and thank you my good sir for reporting it. I will now proceed with my penance and use nothing but Windows ME on my computer for the following month, as an atonement of my sins.
